name = "babyboogey"
main = ".open-next/worker.js"
workers_dev = true
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "babyboogey-db"
database_id = "400a1494-f1dd-41fc-86d4-81c4c51e3948"

[observability]
enabled = true

[vars]
# app
NEXT_PUBLIC_APP_URL = "https://babyboogey.com"
NEXT_PUBLIC_APP_NAME = "AI Baby Dance Generator"

# theme
NEXT_PUBLIC_THEME = "default"

# appearance
NEXT_PUBLIC_APPEARANCE = "system"

# logo
NEXT_PUBLIC_APP_LOGO = "/logo.png"
NEXT_PUBLIC_APP_PREVIEW_IMAGE = "/preview.png"

# database
DATABASE_PROVIDER = "d1"
DB_SINGLETON_ENABLED = "true"
DB_MAX_CONNECTIONS = "1"
