name = "babyboogey"
main = ".open-next/worker.js"
workers_dev = true
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "babyboogey-db"
database_id = "400a1494-f1dd-41fc-86d4-81c4c51e3948"
migrations_dir = "src/config/db/migrations-d1"

[[r2_buckets]]
binding = "NEXT_CACHE_BUCKET"
bucket_name = "babyboogey-cache"

[observability]
enabled = true

[vars]
# app
NEXT_PUBLIC_APP_URL = "https://babyboogey.com"
AUTH_TRUSTED_ORIGINS = "https://babyboogey.com,https://babyboogey.21131911496283.workers.dev"
NEXT_PUBLIC_APP_NAME = "AI Baby Dance Generator"

# theme
NEXT_PUBLIC_THEME = "default"

# appearance
NEXT_PUBLIC_APPEARANCE = "system"

# logo
NEXT_PUBLIC_APP_LOGO = "/logo.png"
NEXT_PUBLIC_APP_PREVIEW_IMAGE = "/preview.png"

# database
DATABASE_PROVIDER = "d1"
DB_SINGLETON_ENABLED = "true"
DB_MAX_CONNECTIONS = "1"
